name: Generate QR Code for Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-qr:
    runs-on: ubuntu-latest

    steps:
    # Clona el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura Python para generar el código QR
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    # Instala las dependencias necesarias
    - name: Install dependencies
      run: pip install qrcode[pil]

    # Genera el código QR
    - name: Generate QR Code
      run: |
        python -c "
import qrcode;
url = 'https://github.com/${{ github.repository }}';
qr = qrcode.QRCode(version=1, box_size=10, border=5);
qr.add_data(url);
qr.make(fit=True);
img = qr.make_image(fill='black', back_color='white');
img.save('repo_qr.png')"

    # Sube el código QR al repositorio
    - name: Commit and push QR code
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        mv repo_qr.png qr_codes/repo_qr.png
        git add qr_codes/repo_qr.png
        git commit -m "Updated QR Code for the repo"
        git push
